In [1]:
import pandas as pd

In [8]:
path = r"H:\Python\Etapa3\AnaliseTabela4\CD2022_Populacao_2010_Compatibilizada_20231222.xlsx"

In [9]:
dados_brutos = pd.read_excel(path, header=2)

In [30]:
tabela_tratada = dados_brutos.iloc[0:5570,1:]

In [33]:
tabela_tratada.columns

Index(['UF', 'COD. UF', 'COD. MUNIC', 'NOME DO MUNICÍPIO',
       'População Município 2010\n(Sinopse)',
       'População 2010 (Alterações de Limites até 2022)1',
       'População Censo 2022', 'DIFERENCA', 'diferenca'],
      dtype='str')

In [35]:
tabela_tratada

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022,DIFERENCA,diferenca
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0,-1139.0
...,...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1395.0,1395.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,245222.0,245222.0

In [12]:
# 5. Crie uma tabela de população agregada por estado
pop_estado = dados_brutos.groupby("UF")[["População 2010 (Alterações de Limites até 2022)1", "População Censo 2022"]].sum().reset_index()

# Faz a diferença (crescimento populacional)
pop_estado["diferenca"] = pop_estado["População Censo 2022"] - pop_estado["População 2010 (Alterações de Limites até 2022)1"]

In [13]:
# 6. Organize essa tabela por população que mais cresceu (Decrescente)
pop_estado_ordenado = pop_estado.sort_values(by="diferenca", ascending=False)

In [14]:
# 7. Salve essa tabela nova em csv na pasta do seu projeto
pop_estado_ordenado.to_csv("populacao_agregada_estado.csv", sep=";", index=False)

In [37]:
pop_estado_ordenado

,UF,População 2010 (Alterações de Limites até 2022)1,População Censo 2022,DIFERENCA
27,SP,41262199.0,44411238.0,3149039.0
25,SC,6248436.0,7610361.0,1361925.0
9,GO,6001789.0,7056495.0,1054706.0
19,PR,10444526.0,11444380.0,999854.0
11,MG,19597330.0,20539989.0,942659.0
13,MT,3035122.0,3658649.0,623527.0
15,PA,7581051.0,8120131.0,539080.0
2,AM,3483985.0,3941613.0,457628.0
5,CE,8451644.0,8794957.0,343313.0
7,ES,3514952.0,3833712.0,318760.0
12,MS,2449024.0,2757013.0,307989.0
17,PE,8796055.0,9058931.0,262876.0
6,DF,2572159.0,2817381.0,245222.0
16,PB,3766528.0,3974687.0,208159.0
10,MA,6574789.0,6776699.0,201910.0
24,RS,10693929.0,10882965.0,189036.0
23,RR,450479.0,636707.0,186228.0
18,PI,3119097.0,3271199.0,152102.0
26,SE,2067852.0,2210004.0,142152.0
21,RN,3168027.0,3302729.0,134702.0
28,TO,1383445.0,1511460.0,128015.0
4,BA,14017071.0,14141626.0,124555.0
0,AC,733559.0,830018.0,96459.0
20,RJ,15989929.0,16055174.0,65245.0
3,AP,669526.0,733759.0,64233.0
22,RO,1562409.0,1581196.0,18787.0
1,AL,3120887.0,3127683.0,6796.0
8,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,0.0,0.0,0.0
14,Nota: Para o cálculo das taxas de crescimento ...,0.0,0.0,0.0

In [23]:
# 8. Agora trabalhe por município
# Faz a diferença diretamente na tabela bruta
dados_brutos["diferenca"] = dados_brutos["População Censo 2022"] - dados_brutos["População 2010 (Alterações de Limites até 2022)1"]

In [24]:
# 9. Organize essa tabela por população que mais cresceu (Decrescente)
pop_municipio_ordenado = dados_brutos.sort_values(by="diferenca", ascending=False)

In [25]:
# 10. Salve essa tabela nova em csv na pasta do seu projeto
pop_municipio_ordenado.to_csv("populacao_municipio_ordenado.csv", sep=";", index=False)

In [38]:
pop_municipio_ordenado[["UF", "NOME DO MUNICÍPIO", "DIFERENCA"]]

,UF,NOME DO MUNICÍPIO,DIFERENCA
111,AM,Manaus,261675.0
5569,DF,Brasília,245222.0
3829,SP,São Paulo,198496.0
3848,SP,Sorocaba,136866.0
5417,GO,Goiânia,135454.0
...,...,...,...
2162,BA,Salvador,-257978.0
5570,NaN,NaN,NaN
5571,Nota: Para o cálculo das taxas de crescimento ...,NaN,NaN
5572,NaN,NaN,NaN
5573,Fonte: IBGE. Diretoria de Pesquisas - DPE - C...,NaN,NaN